packages/schematics/src/sink/dryrun.ts, packages/schematics/src/sink/sink.ts, packages/schematics/src/sink/virtual-filesystem.ts
=> Don't import from 'rxjs'

packages/schematics/angular/collection.json, packages/schematics/angular/interface/files/__path__/__name@dasherize____type__.ts, packages/schematics/angular/interface/index.ts, packages/schematics/angular/interface/schema.json
@Brocco can you check this out and let me know if I got everything please? 😄
=> Ng schematics interface

package-lock.json, package.json, packages/angular_devkit/build_optimizer/package.json, packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts, packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts, packages/angular_devkit/build_optimizer/src/build-optimizer/cli.ts, packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts, packages/angular_devkit/build_optimizer/src/helpers/transform-javascript.ts
=> Fix sourcemap chaining

packages/angular_devkit/build_optimizer/src/build-optimizer/cli.ts, packages/angular_devkit/build_optimizer/src/purify/cli.ts
=> fix(@angular-devkit/build-optimizer): make cli logging consistent

.circleci/config.yml, scripts/test.ts
See individual commits for details.
=> Test improvements

packages/schematics/angular/application/other-files/app.component.html
https://github.com/angular/angular-cli/pull/7387
=> fix(@schematics/angular): correct blog link to blog.angular.io

packages/schematics/angular/application/files/__path__/main.ts
This one is recommended in the style guide. https://angular.io/guide/styleguide#style-02-05 If it's part of the blueprint, it'd be better.
=> fix(@schematics/angular): Add error handling to bootstrapping logic

packages/schematics/angular/application/index.ts
fixes angular/angular-cli#7440
=> fix(@schematics/angular): Use prefix for root component

packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/module/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts, packages/schematics/angular/module/index_spec.ts, packages/schematics/angular/module/schema.json
fixes angular/angular-cli#7524
=> fix(@schematics/angular): Correct routing scope for new projects

packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
fixes angular/angular-cli#7438
=> fix(@schematics/angular): Correct schema path issue with extends.

package.json, packages/angular_devkit/build_optimizer/package.json, packages/angular_devkit/build_optimizer/src/purify/webpack-plugin.ts
=> fix(@angular-devkit/build-optimizer): support disabled webpack cache

packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts, packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
Fixes https://github.com/angular/angular/issues/19113.
It looks like the new versions of TS and tsickle transpile slightly differently. Previously, decorators and constructor parameters were left at the top level:
```ts
var ApplicationRef_ = (function (_super) {
...
}(ApplicationRef));
ApplicationRef_.decorators = [...];
ApplicationRef_.ctorParameters = function () {...};
```
Now the decorators and constructor parameters are nested inside the IIFE:
```ts
var ApplicationRef_ = (function (_super) {
...
ApplicationRef_.decorators = [...];
ApplicationRef_.ctorParameters = function () {...};
}(ApplicationRef));
```
Build-optimizer was only doing a shallow check (on the top level) for expression statements, so it couldn't find the decorators nested in the IIFEs to remove them. Building …
=> fix(@angular-devkit/build-optimizer): fix decorator scrubbing with 2.4

packages/schematics/angular/application/files/__dot__angular-cli.json
=> fix(@schematics/angular): Add missing exclude rule for linting

packages/schematics/angular/application/files/README.md
…run end-to-end tests from README
=> fix(@schematics/angular): remove old ng e2e information

packages/schematics/angular/application/other-files/app.component.ts
Add missing router-outlet in inline AppComponent.
Fixes angular/angular-cli#7701
=> fix(@schematics/angular): restore router-outlet

packages/angular_devkit/build_optimizer/src/helpers/transform-javascript.ts
In initial tests, this PR provided an approximate 40% overall performance improvement.
=> refactor(@angular-devkit/build-optimizer): optimize javascript transform process

packages/schematics/angular/service/schema.json
Closes this issue:
https://github.com/angular/angular-cli/issues/7679
=> fix(@schematics/angular): fix inconsistency in service schema

packages/angular_devkit/build_optimizer/src/purify/purify.ts, packages/angular_devkit/build_optimizer/src/purify/purify_spec.ts, packages/angular_devkit/build_optimizer/src/purify/webpack-plugin.ts
=> fix(@angular-devkit/build-optimizer): fix purify sourcemaps

packages/schematics/angular/enum/files/__path__/__name@dasherize__.enum.ts
Fixes: https://github.com/angular/angular-cli/issues/7639
=> fix(@schematics/angular): create an enum when using enum schematic

packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
Fixes loading external collections with extends
=> fix(@angular-devkit/schematics): fix extends to properly load external collections

packages/schematics/angular/component/index.ts, packages/schematics/angular/component/index_spec.ts, packages/schematics/angular/pipe/index.ts, packages/schematics/angular/pipe/index_spec.ts
fixes angular/angular-cli#7852
=> fix(@schematics/angular): Allow declaration to routing modules

packages/angular_devkit/core/node/resolve.ts, packages/angular_devkit/schematics/tools/file-system-utility.ts, packages/angular_devkit/schematics/tools/node-module-engine-host.ts
So we try more local options for finding the package.json. Also special case
package.json as its not normally resolved by resolve itself.
=> feat(@angular-devkit/schematics): go further in the caller list

packages/schematics/angular/component/index.ts, packages/schematics/angular/component/index_spec.ts, packages/schematics/angular/directive/index.ts, packages/schematics/angular/directive/index_spec.ts, packages/schematics/angular/guard/index.ts, packages/schematics/angular/guard/index_spec.ts, packages/schematics/angular/module/index.ts, packages/schematics/angular/module/index_spec.ts, packages/schematics/angular/pipe/index.ts, packages/schematics/angular/pipe/index_spec.ts, packages/schematics/angular/service/index.ts, packages/schematics/angular/service/index_spec.ts, packages/schematics/angular/utility/prevent-name-duplication.ts, packages/schematics/angular/utility/prevent-name-duplication_spec.ts
fixes angular/angular-cli#7861
=> fix(@schematics/angular): Prevent duplicate names

packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts, packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts, packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts, packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
This reverts commit 06c63f20a079082a760ccb5537eb450c7aa17362.
=> Revert "feat(@angular-devkit/build-optimizer): support es2015 modules"

packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts
General cleanup plus support for TS 2.5
=> refactor(@angular-devkit/build-optimizer): use stricter downlevel class criteria

packages/angular_devkit/build_optimizer/src/purify/webpack-plugin.ts
=> refactor(@angular-devkit/build-optimizer): only replace purify asset if needed

packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts, packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts, packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts, packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
Thanks to @gkalpak for the regex fix 👍
=> Re-add es2015 support and fix es5 detection

packages/angular_devkit/build_optimizer/src/index.ts
=> fix(@angular-devkit/build-optimizer): fix public api exports

packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts, packages/angular_devkit/build_optimizer/src/transforms/prefix-classes_spec.ts
Increases the test coverage to include test cases for TS 2.0 - 2.5.
Partially address #184
=> Additional Prefix Class Transformer Improvements

packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts, packages/angular_devkit/build_optimizer/src/transforms/prefix-classes_spec.ts
=> fix(@angular-devkit/build-optimizer): update regex to allow new cases

.circleci/config.yml
See https://github.com/angular/angular-cli/pull/7872#discussion_r142545247
=> ci: remove cache by branch

packages/schematics/angular/component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
fixes https://github.com/angular/angular-cli/issues/7982
=> fix(@schematics/angular): fix capitalization in inline template

packages/schematics/angular/application/other-files/app.component.ts
To be the same as the separate HTML file.
Fixes https://github.com/angular/angular-cli/issues/8005
=> fix(@schematics/angular): fix the inline template

rules/defocusRule.ts, tslint.json
Per discussion with @filipesilva
=> refactor: add lint checks for fdescribe and fit tests

packages/angular_devkit/schematics/src/engine/schematic_spec.ts, packages/angular_devkit/schematics/src/index.ts, packages/angular_devkit/schematics/src/rules/base.ts, packages/angular_devkit/schematics/src/rules/call.ts, packages/angular_devkit/schematics/src/tree/delegate.ts, packages/angular_devkit/schematics/src/tree/interface.ts, packages/angular_devkit/schematics/src/tree/null.ts, packages/angular_devkit/schematics/src/tree/virtual.ts, packages/angular_devkit/schematics/src/tree/virtual_spec.ts, packages/angular_devkit/schematics/testing/schematic-test-runner.ts, packages/schematics/angular/application/index_spec.ts
I added it as a property of UnitTestTree so it can be used for testing
where its actually useful. Otherwsie the visit() function acts in a
similar fashion.
=> refactor: remove files property

packages/angular_devkit/build_optimizer/README.md, packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts, packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts, packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
=> Remove decorator metadata

packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts, packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
=> fix(@angular-devkit/build-optimizer): wrap tsickle enums

packages/schematics/angular/application/files/package.json
=> feat(@schematics/angular): update Angular version to 5.0.0

packages/schematics/angular/component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts, packages/schematics/angular/component/index_spec.ts
Fixes angular/angular-cli#8082
=> fix(@schematics/angular): Set encaptulation value correctly

packages/schematics/angular/component/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
Fixes: angular/angular-cli#8374
=> fix(@schematics/angular): Correct imports of ViewEncapsulation

packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/application/schema.json, packages/schematics/angular/component/index_spec.ts, packages/schematics/angular/component/schema.json, tests/@angular_devkit/build_optimizer/webpack/simple-app/src/app/app.component.ts
Fixes: angular/angular-cli#8398
=> fix(@schematics/angular): Update default encapsulation value.

packages/schematics/angular/application/files/package.json
Fixes angular/angular-cli#8507
=> fix(@schematics/angular): Remove dep @angular/http

packages/schematics/angular/application/files/package.json
This reverts commit cf70df19c2f419c87871aa66d7bc821ff7751a73.
=> revert: fix(@schematics/angular): Remove dep @angular/http

packages/schematics/angular/utility/route-utils.ts
Fixes angular/angular-cli#8084
=> fix(@schematics/angular): Correct positioning of imports

packages/angular_devkit/schematics/bin/schematics.ts, packages/schematics/schematics/blank/factory.ts, packages/schematics/schematics/blank/project-files/README.md, packages/schematics/schematics/blank/project-files/__dot__gitignore, packages/schematics/schematics/blank/project-files/package.json, packages/schematics/schematics/blank/project-files/src/collection.json, packages/schematics/schematics/blank/project-files/tsconfig.json, packages/schematics/schematics/blank/schema.d.ts, packages/schematics/schematics/blank/schema.json, packages/schematics/schematics/blank/schematic-files/src/__name@dasherize__/index.ts, packages/schematics/schematics/blank/schematic-files/src/__name@dasherize__/index_spec.ts, packages/schematics/schematics/collection.json, scripts/build.ts
This will create a new project if the collection cannot be found, or add
a new schematics to the current project if it can.
=> feat(@schematics/schematics): add a blank schematics

packages/schematics/angular/app-shell/index.ts
=> fix(@schematics/angular): Make app-shell messages consistent

packages/angular_devkit/schematics/src/tree/delegate.ts, packages/schematics/angular/app-shell/index.ts, packages/schematics/angular/app-shell/index_spec.ts
=> fix(@schematics/angular): Use existing universal app if it exists.

packages/schematics/angular/application/other-files/app.module.ts
This PR requires https://github.com/angular/angular/pull/20720 to be released before it should be merged.
=> WIP: fix(@schematics/angular): add ServiceWorkerModule in dev mode, but disabled

packages/schematics/angular/app-shell/index.ts, packages/schematics/angular/app-shell/index_spec.ts
=> fix(@schematics/angular): App shell requires router-outlet

packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts, packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts
Fix https://github.com/angular/angular-cli/issues/8526
Fix https://github.com/angular/angular-cli/issues/8737
=> fix(@angular-devkit/build-optimizer): fix sourcemap chaining

packages/angular_devkit/schematics/src/engine/schematic.ts, packages/angular_devkit/schematics/src/rules/call.ts, packages/angular_devkit/schematics/testing/schematic-test-runner.ts
Fixes #271. There cannot be a test for returning this (yet) as it requires 2 different versions of RXJS.
=> Various QoL: Various fixes

packages/schematics/angular/application/files/__dot__gitignore
=> fix(@schematics/angular): add dist-server in .gitignore

packages/schematics/angular/application/files/package.json
=> feat(@schematics/angular): update tslint to 5.8.0 #347

packages/schematics/angular/application/files/package.json
Artifact of #337 .
typescript 2.5.x needs ng 5.1.x
=> feat(@schematics/angular): typescript 2.5.x needs ng 5.1.0

.circleci/config.yml, WORKSPACE, packages/angular_devkit/core/BUILD, packages/angular_devkit/schematics/BUILD
use the new default tsconfig option as well.
=> build: update to bazel 0.9

packages/schematics/angular/utility/ast-utils.ts
Fixes angular/angular-cli#8520
=> fix(@schematics/angular): Use correct TS position functions.

packages/schematics/angular/application/files/package.json
update tslint to 5.9.1
changelog: https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v591
=> feat(@schematics/angular): update tslint to 5.9.1

packages/schematics/angular/universal/index.ts, packages/schematics/angular/universal/index_spec.ts
=> fix(@schematics/angular): Add universal outDir to gitignore.

packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
Closes #381
Closes angular/angular-cli/issues/9186
=> fix(@angular-devkit/build-optimizer): limit ignore test to safe transformers

packages/angular_devkit/build_optimizer/package.json, packages/angular_devkit/core/package.json, packages/angular_devkit/schematics/package.json, packages/angular_devkit/schematics_cli/package.json, packages/schematics/angular/package.json, packages/schematics/package-update/package.json, packages/schematics/schematics/package.json
=> build: cleanup package dependencies

packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts, packages/angular_devkit/build_optimizer/src/transforms/import-tslib.ts
Fixes #403
Fixes angular/angular-cli#9244
=> fix(@angular-devkit/build-optimizer): limit actions on webpack bundles

lib/bootstrap-local.js
Similar to https://github.com/angular/angular-cli/pull/9302
=> ci: ignore builtin modules

packages/angular_devkit/schematics/testing/schematic-test-runner.ts, packages/schematics/angular/app-shell/index_spec.ts, packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/universal/index_spec.ts
This adds a helper method to the UnitTestTree and should fix angular/angular-cli#8989
=> Test refactor and remove unnecessary code

packages/schematics/angular/application/files/package.json
Upgrade the following devDependencies packages:
```json
"jasmine-core": "~2.99.1",
"protractor": "~5.3.0",
"ts-node": "~5.0.0",
"codelyzer": "~4.1.0",
```
=> upgrade jasmine to 2.99, ts-node to 5.0 and protractor to 5.3.0

packages/schematics/angular/application/files/package.json
=> Revert "upgrade jasmine to 2.99, ts-node to 5.0 and protractor to 5.3.0"

.circleci/config.yml, packages/angular_devkit/build_webpack/test/browser/rebuild_spec_large.ts, packages/angular_devkit/build_webpack/test/karma/code-coverage_spec_large.ts
=> ci: increase timeouts for flaky tests

package-lock.json, package.json, packages/angular_devkit/build_webpack/package.json
One less webpack 4 peer dep warning
=> refactor(@angular-devkit/build-webpack): update webpack sri plugin

.circleci/config.yml, package.json, packages/angular_devkit/build_webpack/test/browser/aot_spec_large.ts, packages/angular_devkit/build_webpack/test/browser/rebuild_spec_large.ts, packages/angular_devkit/build_webpack/test/utils/run-target-spec.ts, packages/angular_devkit/core/src/virtual-fs/path.ts, packages/ngtools/webpack/src/angular_compiler_plugin.ts, packages/ngtools/webpack/src/compiler_host.ts
Followup to https://github.com/angular/devkit/pull/525
=> VFS followup

packages/angular_devkit/build_webpack/src/browser/index.ts
The browser builder was not building after deleting the output dir. It now does the same as the server builder.
=> fix(@angular-devkit/build-webpack): always build after delete dir

package-lock.json, package.json, packages/angular_devkit/build_webpack/package.json, packages/angular_devkit/build_webpack/test/browser/styles_spec_large.ts, packages/schematics/angular/application/files/browserslist, tests/@angular_devkit/build_webpack/hello-world-app/browserslist
browserslist defaults are based on the Angular support browsers: https://angular.io/guide/browser-support
=> refactor(@angular-devkit/build-webpack): update autoprefixer to v8.1

packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts, packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts, packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts, packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts, packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/test.ts, packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts, packages/angular_devkit/build_angular/src/browser/index.ts, packages/angular_devkit/build_angular/src/karma/index.ts, packages/angular_devkit/build_angular/src/server/index.ts
incremental improvement to type information as well as removed some redundant properties
=> refactor(@angular-devkit/build-angular): cleanup webpack config types

packages/angular_devkit/core/src/json/schema/registry.ts, packages/angular_devkit/core/src/json/schema/transforms.ts, packages/angular_devkit/core/src/json/schema/visitor.ts
Smart defaults were overwriting some objects with the wrong ones.
=> fix(@angular-devkit/core): properly chain observables in registry

packages/angular_devkit/schematics/tasks/node-package/executor.ts, packages/angular_devkit/schematics/tasks/node-package/install-task.ts, packages/angular_devkit/schematics/tasks/node-package/options.ts, packages/angular_devkit/schematics/tools/workflow/node-workflow.ts, packages/schematics/angular/migrations/update-6/index.ts
Fixes angular/angular-cli#10154
=> Migrate using project's package manager

packages/schematics/angular/component/index.ts, packages/schematics/angular/component/index_spec.ts, packages/schematics/angular/directive/index.ts, packages/schematics/angular/directive/index_spec.ts, packages/schematics/angular/directive/schema.json, packages/schematics/angular/utility/validation.ts
fixes angular/angular-cli#10144
=> fix(@schematics/angular): Fix selectors when name has a path

packages/schematics/angular/universal/index.ts
Fixes https://github.com/angular/angular-cli/issues/10190
=> fix(@schematics/angular): remove broken imports

packages/angular_devkit/schematics/src/workflow/interface.ts, packages/angular_devkit/schematics/tools/workflow/node-workflow.ts, packages/angular_devkit/schematics_cli/bin/schematics.ts
This will allow us to show logs at each new phases, for example, instead of only at the end.
Reference: https://github.com/angular/angular-cli/issues/10155
=> feat(@angular-devkit/schematics): add lifecycle hooks to workflow

packages/angular_devkit/schematics/tasks/repo-init/executor.ts
Otherwise it does not get proper settings and git cannot find the gitconfig (using HOME).
Fix https://github.com/angular/angular-cli/issues/10201
=> fix(@angular-devkit/schematics): pass the environment to git

packages/angular_devkit/core/src/json/schema/registry.ts, packages/angular_devkit/core/src/json/schema/registry_spec.ts
Fix https://github.com/angular/angular-cli/issues/10187
=> fix(@angular-devkit/core): process schema validation errors when async

packages/angular_devkit/architect/src/architect_spec.ts, packages/angular_devkit/core/src/json/schema/interface.ts, packages/angular_devkit/core/src/json/schema/registry.ts, packages/angular_devkit/core/src/json/schema/registry_spec.ts, packages/angular_devkit/core/src/workspace/workspace.ts, packages/angular_devkit/core/src/workspace/workspace_spec.ts, packages/angular_devkit/schematics/tools/schema-option-transform.ts
This is needed for the improved CLI command option error message support
=> refactor(@angular/cli): expose additional schema validation error data

packages/schematics/angular/package.json
should close #651 
Tested with yarn test and in angular/cli tests.
=> refactor(@schematics/angular): bump TS package dependency version to 2.7

packages/schematics/update/update/index.ts, packages/schematics/update/update/npm.ts, packages/schematics/update/update/schema.json, packages/schematics/update/update/schema.ts
To allow for people that use NPM proxies or local cache and dont have access
to the registry.npmjs.org
Fix angular/angular-cli#10241
=> feat(@schematics/update): add registry flag

packages/schematics/angular/service-worker/index.ts, packages/schematics/angular/service-worker/index_spec.ts
Fixed pull request. To replace https://github.com/angular/devkit/pull/677 + https://github.com/angular/devkit/pull/676
=> fix(@schematics/angular): Correct the service worker package dependency

packages/schematics/angular/migrations/update-6/index.ts
Fixes angular/angular-cli#10226
=> fix(@schematics/angular): add schema link to migrated config

packages/schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.ts, packages/schematics/angular/service/index.ts, packages/schematics/angular/service/index_spec.ts, packages/schematics/angular/service/schema.d.ts, packages/schematics/angular/service/schema.json
fixes angular/angular-cli#10170
CLI related e2e fixes here: angular/angular-cli#10301
=> fix(@schematics/angular): Remove module option from service schematic

packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts, packages/angular_devkit/build_angular/test/browser/index-bom_spec_large.ts, packages/angular_devkit/build_angular/test/utils/test-project-host.ts, packages/angular_devkit/core/src/virtual-fs/host/interface.ts, packages/angular_devkit/core/src/virtual-fs/host/sync.ts
=> fix(@angular-devkit/build-angular): strip and use BOM for index.html

packages/schematics/update/update/index.ts, packages/schematics/update/update/index_spec.ts
Basically, --from=1 is the same as --from=1.0.0.
Fix #660
=> fix(@schematics/update): allow --from and --to to have partial versions

packages/schematics/angular/service-worker/index.ts, packages/schematics/angular/service-worker/index_spec.ts
=> fix(@schematics/angular): Add missing head tags to index.html

packages/angular_devkit/core/src/utils/object.ts, packages/angular_devkit/core/src/utils/object_spec.ts
=> fix(@angular-devkit/core): fix deepCopy entirely

docs/specifications/update.md, packages/schematics/update/update/index.ts
Packages will be reduced to their package name. Added the spec for the new
packageGroupName argument (default to the first item of the packageGroup).
Fixes angular/angular-cli#10248
Fixes angular/angular-cli#10247
=> fix(@schematics/update): group packages together

packages/schematics/angular/application/files/root/karma.conf.js, packages/schematics/angular/library/files/__projectRoot__/karma.conf.js, tests/@angular_devkit/build_angular/hello-world-app/karma.conf.js, tests/@angular_devkit/build_ng_packagr/ng-packaged/projects/lib/karma.conf.js, tests/@angular_devkit/build_webpack/hello-world-app/karma.conf.js
This option isn't used anymore.
=> fix(@schematics/angular): remove unused karma config option

packages/schematics/angular/application/index.ts
Followup to https://github.com/angular/devkit/pull/667
=> fix(@schematics/angular): use string style for new app

packages/angular_devkit/build_angular/src/angular-cli-files/utilities/service-worker/index.ts, packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
Fix https://github.com/angular/angular-cli/issues/10297
=> fix(@angular-devkit/build-angular): fix service worker assets paths

package-lock.json, package.json, packages/angular_devkit/schematics/tools/workflow/node-workflow.ts, packages/angular_devkit/schematics/tools/workflow/node-workflow_spec.ts
Note: I have no idea what the NodeWorkflow test should really look like. I just added it to have something failing that would be fixed by the changes.
Fix https://github.com/angular/angular-cli/issues/10335
=> fix(@angular-devkit/schematics): don't reduce directly on concat

packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts, packages/angular_devkit/build_angular/test/server/base_spec_large.ts, packages/angular_devkit/build_ng_packagr/src/build/index_spec_large.ts
Mainly for AppVeyor flake reduction.
=> test: adjust timeouts for certain more complex tests

packages/schematics/angular/application/index.ts
PR #712 fixed it in a new app, but not in the karma conf.
=> fix(@schematics/angular): use string style for new app in karma

packages/angular/pwa/pwa/index.ts
fixes angular/angular-cli#10332
=> fix(@angular/pwa): Install new dependencies

packages/schematics/angular/class/index.ts, packages/schematics/angular/component/index.ts, packages/schematics/angular/directive/index.ts, packages/schematics/angular/enum/index.ts, packages/schematics/angular/guard/index.ts, packages/schematics/angular/interface/index.ts, packages/schematics/angular/library/index_spec.ts, packages/schematics/angular/module/index.ts, packages/schematics/angular/pipe/index.ts, packages/schematics/angular/service/index.ts
fixes angular/angular-cli#10344
=> fix(@schematics/angular): Fix generation within a library project

packages/angular_devkit/architect/src/architect.ts, packages/angular_devkit/core/src/workspace/workspace-schema.json, packages/angular_devkit/core/src/workspace/workspace-schema.ts, packages/angular_devkit/core/src/workspace/workspace.ts, packages/angular_devkit/core/src/workspace/workspace_spec.ts, packages/schematics/angular/app-shell/index.ts, packages/schematics/angular/application/index.ts, packages/schematics/angular/application/index_spec.ts, packages/schematics/angular/library/index.ts, packages/schematics/angular/library/index_spec.ts, packages/schematics/angular/universal/index.ts, packages/schematics/angular/utility/config.ts
Partially address https://github.com/angular/angular-cli/issues/10352
=> feat(@angular-devkit/core): add default project

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
Fixes: angular/angular-cli#10378
=> fix(@angular-devkit/build-angular): disable sourcemaps with JS styles

packages/ngtools/webpack/src/transformers/export_lazy_module_map.ts, packages/ngtools/webpack/src/transformers/export_lazy_module_map_spec.ts, packages/ngtools/webpack/src/transformers/multiple_transformers_spec.ts
Fix https://github.com/angular/devkit/issues/698
=> fix(@ngtools/webpack): fix relative paths in module map imports

packages/schematics/angular/application/files/root/browserslist
Fixes: angular/angular-cli#10337
=> fix(@schematics/angular): sync browserslist with polyfills

packages/schematics/update/update/index.ts
Everywhere.
Fix angular/angular-cli#10252
=> fix(@schematics/update): fallback to latest if next isnt defined

packages/schematics/angular/migrations/update-6/index.ts
related to angular/angular-cli#10311
=> fix(@schematics/angular): Add npm script warning for after updating

packages/schematics/update/update/index.ts, packages/schematics/update/update/index_spec.ts, tests/schematics/update/packages/update-peer-dependencies-angular-5/package.json
Fix https://github.com/angular/angular-cli/issues/10367
=> fix(@schematics/update): support Angular 6.x when peerDep is 5.x

packages/schematics/angular/migrations/update-6/index.ts, packages/schematics/angular/migrations/update-6/index_spec.ts
Fixes: angular/angular-cli#10473
=> fix(@schematics/angular): migrate style preprocessor options

packages/schematics/angular/application/index.ts, packages/schematics/angular/class/index.ts, packages/schematics/angular/class/index_spec.ts, packages/schematics/angular/class/schema.json, packages/schematics/angular/component/index.ts, packages/schematics/angular/component/index_spec.ts, packages/schematics/angular/component/schema.json, packages/schematics/angular/directive/index.ts, packages/schematics/angular/directive/index_spec.ts, packages/schematics/angular/directive/schema.json, packages/schematics/angular/enum/index.ts, packages/schematics/angular/enum/index_spec.ts, packages/schematics/angular/enum/schema.json, packages/schematics/angular/guard/index.ts, packages/schematics/angular/guard/index_spec.ts, packages/schematics/angular/guard/schema.json, packages/schematics/angular/interface/index.ts, packages/schematics/angular/interface/index_spec.ts, packages/schematics/angular/interface/schema.json, packages/schematics/angular/library/index.ts, packages/schematics/angular/module/index.ts, packages/schematics/angular/module/index_spec.ts, packages/schematics/angular/module/schema.json, packages/schematics/angular/pipe/index.ts, packages/schematics/angular/pipe/index_spec.ts, packages/schematics/angular/pipe/schema.json, packages/schematics/angular/service/index.ts, packages/schematics/angular/service/index_spec.ts, packages/schematics/angular/service/schema.json
=> fix(@schematics/angular): Resolve project by new smart default provider.

packages/schematics/update/update/index.ts, packages/schematics/update/update/index_spec.ts, tests/schematics/update/packages/update-peer-dependencies-angular-5-2/package.json
When there are complex ranges, ltr(x) is not equal to !gtr(x).
Fix angular/angular-cli#10540
=> fix(@schematics/update): fix major of angular compat with major + 1

packages/schematics/angular/application/files/src/polyfills.ts
Fixes: angular/angular-cli#10522
/cc @matsko
=> fix(@schematics/angular): update animations polyfill instructions

packages/schematics/angular/migrations/update-6/index.ts, packages/schematics/angular/migrations/update-6/index_spec.ts
Fix https://github.com/angular/angular-cli/issues/10581
=> fix(@schematics/angular): set defaultProject on update

packages/schematics/angular/migrations/update-6/index.ts, packages/schematics/angular/migrations/update-6/index_spec.ts
Fix https://github.com/angular/angular-cli/issues/10489
=> fix(@schematics/angular): migrate 1.0 karma configs

packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts, packages/angular_devkit/build_angular/src/karma/index.ts, packages/angular_devkit/build_angular/src/karma/schema.json
Fixes #847
Fixes https://github.com/angular/angular-cli/issues/10623
=> feat(@angular-devkit/build-angular): allow optional karma watch

packages/schematics/angular/guard/files/__name@dasherize__.guard.ts
@hansl @Brocco @filipesilva 
Fixes angular/angular-cli#10509
=> fix(@schematics/angular): providedIn in guard

packages/schematics/update/update/index.ts, packages/schematics/update/update/index_spec.ts
Fix https://github.com/angular/angular-cli/issues/10356
=> fix(@schematics/update): respect caret and tilde ranges

packages/angular_devkit/build_angular/package.json
Closes: angular/angular-cli#10738
=> refactor(@angular-devkit/build-angular): make node-sass optional

packages/schematics/angular/ng-new/schema.json
This PR works in conjunction with angular/angular-cli#10851
=> fix(@schematics/angular): Fix new project default options

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
fix for https://github.com/angular/angular-cli/issues/10744
=> support mjs extension

packages/schematics/schematics/blank/project-files/package.json
=> fix(@schematics/schematics): should not have test node_modules specs

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts, packages/angular_devkit/build_angular/test/server/base_spec_large.ts
Fixes: angular/angular-cli#10680
=> fix(@angular-devkit/build-angular): support server sourcemaps

packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts, packages/angular_devkit/build_angular/test/browser/index_spec_large.ts, packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
Fixes: angular/angular-cli#10696
Fixes: angular/angular-cli#10819
=> fix(@angular-devkit/build-angular): perform surgical updates to index.html

package-lock.json, package.json, scripts/changelog.ts, scripts/templates/changelog-feat.ejs, scripts/templates/changelog-fix.ejs, scripts/templates/changelog-special-thanks.ejs, scripts/templates/changelog.ejs
e.g. to use: 
```sh
devkit-admin changelog --from=v6.0.0 --to=v6.0.1 --githubToken=123abcdef
```
This will create a draft release on Github.
=> ci: add changelog generator

packages/angular_devkit/build_angular/src/dev-server/index.ts
Fixes: angular/angular-cli#10886
=> fix(@angular-devkit/build-angular): make serve build options override

packages/schematics/angular/library/index.ts, packages/schematics/angular/library/index_spec.ts
Closes: angular/angular-cli#10665
=> Library schematic fixes

packages/angular_devkit/core/src/json/schema/interface.ts, packages/angular_devkit/core/src/json/schema/transforms.ts, packages/angular_devkit/core/src/json/schema/visitor.ts, packages/angular_devkit/core/src/virtual-fs/host/test.ts, packages/angular_devkit/schematics/tools/file-system-engine-host.ts, packages/angular_devkit/schematics/tools/node-module-engine-host.ts, packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
This is the first commit of #924. The linting rule is too slow for this project and this is blocking google3 sync.
=> ci: fix all circular dependencies

packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts, packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts, packages/ngtools/webpack/src/angular_compiler_plugin.ts
This allows for mixed Angular and React code in the same project, and should address angular/angular-cli#8046.
If you wish to merge it and need me to add tests or anything, please let me know and I will try to do so ASAP. Thanks :)
=> feat(@ngtools/webpack): add .tsx support

packages/schematics/angular/migrations/update-6/index.ts, packages/schematics/angular/migrations/update-6/index_spec.ts
fixes angular/angular-cli#10915
=> fix(@schematics/angular): Transfer baseHref when during update process
