angular/devkit

- packages/schematics/angular/collection.json
- packages/schematics/angular/service/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts
- packages/schematics/angular/service/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.ts
- packages/schematics/angular/service/index.ts
- packages/schematics/angular/service/schema.json
Have a `TODO` in there for the module name option as per discussion with @Brocco. Also, the `package-lock.json` file is in here. Not sure what the plan is to handle that as it changes from dev to dev. Let me know if I need to do anything on that.
> Ng schematics service

- packages/schematics/angular/collection.json
- packages/schematics/angular/pipe/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.pipe.spec.ts
- packages/schematics/angular/pipe/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.pipe.ts
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/pipe/schema.json
The `module` option still needs to be implemented. I didn't see an example of that yet in the `component` schematic so I am not sure how the desired implementation should go (looks like it will probably need a `resolveModulePath` utility function).
@Brocco can you check this out and let me know if I got everything (besides the `module` option) please? 😄
> Ng schematics pipe

- package-lock.json
- package.json
We're not using it and it was showing a missing peerDep for `marked`.
> build: remove marked-terminal

- packages/angular_devkit/schematics/src/engine/interface.ts
- packages/angular_devkit/schematics/src/rules/schematic.ts
fix the SchematicImpl class incorrectly implementing the Schematic interface
resolve issue #75
> fix(@angular-devkit/devkit): fix incorrect implementation of schematic interface

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
Fix #78
Fix https://github.com/angular/angular-cli/issues/7280
> fix(@angular-devkit/build-optimizer): don't optimizer service-worker

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
The `@angular/cdk` package should be included in the Angular whitelist to avoid size regression in AIO.
> fix(@angular-devkit/build-optimizer): add cdk to angular whitelist

- lib/packages.ts
https://github.com/angular/devkit/pull/83 added some regexes that weren't windows safe, this fixes it.
> build: fix package build on windows

- packages/schematics/angular/component/index.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/pipe/index.ts
We check for options.module so that the type checking knows module isnt optional anymore.
> refactor(@schematics/angular): remove unused code

- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/utility/find-module.ts
1. when not passing --module, guard should not try to import it
2. fix regression with --module logic, which allows to pass a path
> fix(@schematics/angular): 2 fixes

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
When this library was first created it was restricted to FESM5 files (`*.es5.js`) and the Angular package directories were hard-coded. We are moving things around and so the restrictions are being loosened to include everything in the `@angular` directory.
This will eventually go away when we support reading the pure imports from package.json.
> fix(build-optimizer): remove restriction to *.es5.js

- packages/angular_devkit/schematics/tools/file-system-host.ts
It was not working because the first path is "", not "/".
> fix(@angular-devkit/schematics): fix node_modules and .git filtering

- packages/angular_devkit/build_optimizer/src/purify/webpack-plugin.ts
This PR fixes the filter in the NGO purify plugin to include files that end in .js instead of .bundle.js.
I discussed this PR with @filipesilva on slack.
Thanks,
Dan
> Fix the filter for ngo's purify webpack plugin

- packages/schematics/angular/utility/find-module.ts
- packages/schematics/angular/utility/find-module_spec.ts
Fixes https://github.com/angular/angular-cli/issues/7631
> fix(@schematics/angular): fix find module when using non-normalized paths

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
There is a hard-coded sourceDir expectation in the code, this removes it
in favor of using the appropriate value from options.
Fixes https://github.com/angular/angular-cli/issues/7656
> fix(@schematics/angular): fix application sourceDir option

- packages/schematics/angular/application/files/tslint.json
It's a copy/paste of this [PR](https://github.com/angular/angular-cli/pull/6651) :
Few codelyzer rules report warnings which are also compile-time errors caught by the
Angular compiler and reported by the language service.
Since codelyzer doesn't aim to provide type checking and deep analysis
of the entire project, it'll be better if these two rules are removed.
Btw, soon more rules will follow mgechev/codelyzer#314.
cc/ @mgechev
> feat(@schematics/angular): remove codelyzer rules

- packages/schematics/angular/application/other-files/app.component.html
This change fixes a security/performance issue in links that open in new windows, and by the same token, increases the lighthouse score for PWAs. Assuming we (eventually) want a CLI-generated Angular project to be 100% PWA, this is a necessary change.
> fix(@schematics/angular): fix missing link attribute for PWA

- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
This converts the enum wrapping transformer to use a single pass of the AST and replaces enum declarations inline.  It also attempts to reuse existing structure where possible.  The enum member declaration _finder_ functions were not modified in this PR.
//cc @filipesilva
> refactor(@angular-devkit/build-optimizer): use single pass to wrap enums

- packages/schematics/angular/application/files/__path__/polyfills.ts
`@angular/animation` doesn't exist.
> docs(@schematics/angular): fix wrong package name for animations

- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
Fix https://github.com/angular/angular-cli/issues/7799
> fix(@angular-devkit/build-optimizer): don't add pure to super calls

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
- scripts/validate-commits.ts
This reverts https://github.com/angular/devkit/pull/168 because this es2015 support needed more than that.
> Build optimizer es2015

- lib/packages.ts
- packages/_/benchmark/package.json
- packages/angular_devkit/build_optimizer/package.json
- packages/angular_devkit/core/package.json
- packages/angular_devkit/schematics/package.json
- packages/schematics/angular/package.json
To avoid people going in those directories and running npm install.
Fixes #172.
> build: add a warning in the package.json of each subpackages

- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/class/index_spec.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/enum/index_spec.ts
- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/interface/index_spec.ts
- packages/schematics/angular/module/index_spec.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/service/index_spec.ts
`index.ts` files use `__X__Options` while the `index_spec.ts` files used `__X__Schema`.
Also fixed a typo in the `Service` schematic spec to properly reference it's testing the `Service` schematic.
> refactor: make schema aliases consistent

- package-lock.json
- packages/angular_devkit/core/src/json/schema/schema.ts
- packages/angular_devkit/schematics/tools/description.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host_spec.ts
- packages/angular_devkit/schematics/tools/index.ts
- packages/schematics/angular/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/aliases/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/invalid-aliases-2/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/invalid-aliases/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/null-factory.ts
- tests/@angular_devkit/schematics/tools/file-system-engine-host/works/collection.json
Aliases are supported in the FileSystemEngineHostBase (and derivatives). When a
schematic is resolved the name being resolved will be replaced if a schematic
of the collection has an alias that matches the name.
Having 2 aliases be the same on two different schematics, or having an alias
be the same name as a schematic are both an error.
Also added much needed tests for file-system-engine-host.
> feat(@angular-devkit/schematics): add support for aliases

- packages/angular_devkit/core/node/fs.ts
- packages/angular_devkit/core/src/virtual-fs/path.ts
- packages/angular_devkit/core/src/virtual-fs/path_spec.ts
- packages/angular_devkit/schematics/src/rules/call.ts
- packages/angular_devkit/schematics/src/sink/dryrun_spec.ts
- packages/angular_devkit/schematics/src/sink/filesystem_spec.ts
- packages/angular_devkit/schematics/src/tree/filesystem.ts
- packages/angular_devkit/schematics/src/tree/filesystem_spec.ts
- packages/angular_devkit/schematics/src/tree/filtered.ts
- packages/angular_devkit/schematics/src/tree/filtered_spec.ts
- packages/angular_devkit/schematics/src/tree/interface.ts
- packages/angular_devkit/schematics/src/tree/null.ts
- packages/angular_devkit/schematics/src/tree/virtual.ts
- packages/angular_devkit/schematics/src/tree/virtual_spec.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
- packages/angular_devkit/schematics/tools/file-system-host.ts
- packages/schematics/angular/utility/find-module.ts
This is the performance improvement PR. Refactor the filesystem to remove the need to use `files`. `files` itself is not going away just yet (because it's useful for tests) but will tomorrow after this PR makes it in.
> Perf simple

- packages/schematics/angular/application/files/tslint.json
This PR adds `rxjs/Rx` into `import-blacklist` array in `tslint.ts` for reasons explained in angular/angular-cli#7591.
> fix(@angular/schematics): add rxjs/Rx into tslint.ts import-blacklist

- packages/schematics/angular/application/files/__dot__angular-cli.json
If a create an app with the CLI with the `--inline-template` option, I don't just want the `AppComponent` with inline template, I surely want inline templates everywhere.
Same goes for `--inline-style` and `--skip-tests`.
So this PR save the options used during `ng new`, which are related to future generate commands, as defaults in `.angular-cli.json`.
This is particularly helpful for beginners : skipping tests (= less files to mess with) and inlining templates (easier to see relations between class and view) is better to learn at first, but having to reconfigure the `.angular-cli.json` after the `ng new` is cumbersome, especially when people don't understand yet at this time what they are configuring.
I just need confirmation that `||` and `&&` operators work here, but I suppose the …
> feat(@schematics/angular): save ng new options as defaults

- packages/schematics/angular/application/files/__dot__angular-cli.json
The current order is not sorted alphabetically. so `.angular-cli.json` will make diff after `ng set` command.
> fix(@schematics/angular): Sort defaults alphabetically

- packages/schematics/angular/application/files/__path__/polyfills.ts
Only IE11 and less needs it. See http://kangax.github.io/compat-table/es6/#test-Reflect
Fixes #206.
> fix(@schematics/angular): remove the Reflect polyfill

- packages/schematics/angular/application/files/__dot__angular-cli.json
Fixes PR #213 which sorted the options without taking the conditions into consideration, resulting in `class: { spec: false }` for everyone.
Fixes PR #196 comma position.
> fix(@schematics/angular): missing condition and comma position

- packages/angular_devkit/build_optimizer/src/build-optimizer/webpack-loader.ts
Some sourcemaps do not have file attribute (which points to the file the sourcemap is
relating to anyway, not the source sourcemap). Those files used to map to "undefined",
not anymore.
> fix(@angular-devkit/build-optimizer): use the real sourcemaps

- packages/schematics/angular/application/files/__path__/ngsw-config.json
- packages/schematics/angular/application/files/package.json
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/other-files/app.module.ts
- packages/schematics/angular/application/schema.d.ts
- packages/schematics/angular/application/schema.json
This adds a feature to the Angular application schematic to generate a
project which includes @angular/service-worker's ServiceWorkerModule,
conditionally enabled for production builds. An ngsw.json file with
configuration suited for most projects is also generated.
Both operations are gated on the --service-worker flag which is added.
> feat(@schematics/angular): service worker project generation

- packages/schematics/angular/application/files/__dot__angular-cli.json
CLI 1.6.0-beta.0 still needs service worker app option to build it.
@hansl @filipesilva @Brocco
> fix(@schematics/angular): add app config for service worker

- packages/angular_devkit/schematics/src/tree/filesystem.ts
- packages/angular_devkit/schematics/src/tree/memory-host.ts
- packages/angular_devkit/schematics/src/tree/node-host.ts
- packages/angular_devkit/schematics/tools/file-system-host.ts
This prevents the get, read, and branch calls of the filesystem tree from causing a full walk of the underlying file system host.
> refactor(@angular-devkit/schematics): make filesystem tree get/read/branch lazy

- packages/schematics/angular/application/files/package.json
- packages/schematics/angular/application/files/tslint.json
codelyzer@^4.0.0 is out 🎉! It introduces support for `@angular/compiler` version 5 and few new rules such as:
- `angular-whitespace` - checks whether we have presence of whitespace
in the template to make it more readable, for instance
in `{{ expr }}`, `check-interpolation` will check if `expr` is
surrounded by whitespace. This rule also introduces auto fixes.
- `no-output-on-prefix` - warns if outputs are prefixed with `on` this
is based on
https://angular.io/guide/styleguide#dont-prefix-output-properties.
Tell me what you think about `angular-whitespace` and let me know if it
is too opinionated. As part of `angular-whitespace` we're planning a few
more features.
Also, since `invoke-injectable` is supposed to be caught by `tsc`, this rule has been deprecated.
Fixes …
> feat: update codelyzer and add rules

- packages/schematics/angular/app-shell/index.ts
- packages/schematics/angular/app-shell/index_spec.ts
Recorders are meant to be reused. Unless the refactor needs the new AST, we should
reuse the recorder for modulePath.
> fix(@schematics/angular): use a single recorder

- packages/schematics/angular/application/files/__path__/polyfills.ts
With https://github.com/angular/angular/commit/344a5ca5452bc01a1e5ff8f04aa7a283ce4134cf landed at `5.0.0-rc.0`, Zone.js is no longer a requirement of Angular when using `NoopNgZone`.
<sub>~~There is currently a bug https://github.com/angular/angular/issues/19534 for misusing Zone.js in Angular, so it would give a false alert when not using Zone.js for now.~~ fixed already</sub>
Relates to https://github.com/angular/angular/pull/20121, the requirement statement has been fixed already in Angular itself. Likely the message should be consistent?
> docs(@schematics/angular): adjust statement of Zone.js prolyfill

- packages/schematics/angular/application/files/__path__/polyfills.ts
As the i18n pipes have been rewritten in Angular 5, we shouldn't need the Intl polyfill now.
> fix(@schematics/angular): remove Intl polyfill

- packages/schematics/angular/application/files/tslint.json
Angular uses the ` @deprecated` tag when a function is deprecated. Since Angular's roadmap is intensive, it could be fine to have a warn as soon as possible when we use have a deprecated functionnality in our code.
Tslint can help us !
> feat(@schematics/angular): add deprecation rule

- packages/angular_devkit/build_optimizer/src/purify/purify.ts
- packages/angular_devkit/build_optimizer/src/purify/webpack-plugin.ts
This uses `exec` instead of `replace` and inserts only the pure annotation instead of a full replace.
> refactor(@angular-devkit/build-optimizer): optimize purify plugin

- packages/schematics/angular/application/files/tslint.json
While updating to Codelyzer 4.0, #257 also added a new `angular-whitespace` rule.
This must be reverted because :
- it is a breaking change : existing project are now failing on lint ;
- it is opinionated (it is not in official Angular style guide) and so should not be forced ;
- it is the contrary of what is done in the official Angular doc and in the style guide itself.
@hansl @filipesilva @Brocco @mgechev
> fix(@schematics/angular): revert breaking angular-whitespace lint rule

- packages/angular_devkit/schematics/src/sink/filesystem_spec.ts
- packages/angular_devkit/schematics/src/sink/sink.ts
Actions were ordered wrongly before during commit to the filesystem. Now theyre
properly waited after before being committed, which fixes some inconsistencies.
> fix(@angular-devkit/schematics): fix random ordering of actions

- packages/schematics/angular/application/files/package.json
According to the idea the CLI should be ready to use, if I want to work in dev, I run `npm start`, and if I want to go in production, I run `npm run build`. But currently the build is in dev mode by default, requiring the user to know he/she has to go to modify the npm script accordingly.
@hansl @filipesilva
> fix(@schematics/angular): build in --prod mode by default

- packages/angular_devkit/schematics/src/rules/call.ts
- packages/angular_devkit/schematics/src/rules/call_spec.ts
Add a check if a rule returns an Observable, which will fail if the Observable does not
contain a Tree.
> fix(@angular-devkit/schematics): check that rules/sources return proper value

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
This eliminates several array copying operations as well as making the changes in the 2.3+ case more surgical (i.e., direct minimal modification of the existing IIFE).  The tsickle case is also now more robust.
Fixes https://github.com/angular/angular-cli/issues/8536
> refactor(@angular-devkit/build-optimizer): improve resiliency of enum wrapper

- packages/schematics/angular/application/files/package.json
As Angular 5.1 now supports TS 2.5, this should now be the default TS version.
> feat(@angular/schematics): use TS 2.5

- packages/schematics/package-update/utility/npm_spec.ts
Version `4.1.0` of `@angular/core` allows an `rxjs` version of `^5.0.1`.
> test(@schematics/package-update): relax rxjs version check

- packages/schematics/angular/universal/files/__sourceDir__/__main@stripTsExtension__.ts
Universal build should be in production mode for performance.
It also avoid an issue with Material which produces an error (`window is not defined`) in development mode.
@filipesilva @hansl @Brocco
> fix(@schematics/angular): enable prod mode for universal

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/helpers/transform-javascript.ts
- packages/angular_devkit/build_optimizer/src/transforms/class-fold_spec.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
- packages/angular_devkit/build_optimizer/src/transforms/scrub-file_spec.ts
This provides a transformation fast path when source maps are not enabled and transformers that require the type checker are not needed for a file (`scrub-file`/`fold-file`).  This also has the advantage of not running any of the built-in (and unneeded) transformers when used.
There doesn't appear to be a publicly exposed mechanism to generate source maps with the TS printer.  If this were possible, the source map limitation could be lifted.
> Build Optimizer Lightweight Transformations

- packages/angular_devkit/schematics/src/sink/filesystem.ts
- packages/angular_devkit/schematics/src/sink/filesystem_spec.ts
If the destination directory is not present, the moving of the file would fail. That's why we need to ensure the directory exists before the move/rename.
fixes #352
> fix(@angular-devkit/schematics): create directory when moving file

- packages/schematics/angular/application/files/__sourcedir__/test.ts
- packages/schematics/angular/application/files/package.json
zone.js 0.8.19 provide a `zone-testing` bundle to import 
```javascript
import '../zone-spec/long-stack-trace';
import '../zone-spec/proxy';
import '../zone-spec/sync-test';
import '../jasmine/jasmine';
import '../zone-spec/async-test';
import '../zone-spec/fake-async-test';
```
so  `angular/cli` only need to import `zone.js/dist/zone-testing`, it will also resolve some 
auto load order change issue.
@clydin, should I make this pull request in this repo? please review, thank you.
> feat(test): use new zone-testing import from zone.js 0.8.19

- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
> fix(@schematics/angular): Clear polyfills for universal apps.

- packages/angular_devkit/schematics/src/engine/interface.ts
- packages/angular_devkit/schematics/tools/fallback-engine-host.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
listSchematics was removed and shouldnt have been. Oops.
> fix(@angular-devkit/schematics): add a backward compatible function

- packages/schematics/angular/application/files/tslint.json
I hope this is the file that is used as `tslint.json` while creating new projects with angular-cli
The `typeof-compare` has been deprecated/redundant since `tslint 5.9.1`. Hence removing it
tslint v5.9.1 Changelog: https://github.com/palantir/tslint/releases/tag/5.9.1
> remove deprecated typeof-compare  from tslint.json

- CONTRIBUTING.md
The motivation to allow the `@angular-devkit/schematics-cli` package as a scope in the commit message is because of PRs like this: https://github.com/angular/devkit/pull/391. It's very likely that more changes will be added to this package in the future.
> docs: add schematics-cli package to supported commit scopes

- packages/schematics/angular/application/files/__sourcedir__/tsconfig.spec.json
> fix(@schematics/angular): don't overwrite target for specs

- packages/schematics/angular/application/files/package.json
ng 5.2.x released ~~and supports typescript 2.6.x as well~~. 
More details here at - 
https://blog.angular.io/angular-5-2-now-available-312d1099bd81 . 
Upgrade the generated package.json to refer to 5.2.x
> feat(@schematics/angular): upgrade to ng 5.2.0

- packages/schematics/angular/application/files/package.json
It is not needed. Only when ejecting which is covered by angular/angular-cli#9368
Fixes angular/angular-cli#9294
> fix(@schematics/angular): remove karma-cli

- packages/schematics/angular/application/files/__sourcedir__/polyfills.ts
in `zone.js`, there are some flags which can disable some monkey-patch.
such as 
- disable requestAnimationFrame
- disable onProperty
...
or disable some eventNames such as 
- disable scroll eventName, mousemove.
which can improve performance and can let user do some customized patch.
- update: 2018/1/23, sync the flag list with `angular.io`, https://github.com/angular/angular/pull/21701
> feat(@schematics/angular): add zone.js flags which can disable some patch

- packages/schematics/angular/application/files/__sourcedir__/polyfills.ts
from `zone.js` 0.8.13, there is a new flag `__Zone_enable_cross_context_check` was added.
- IE/Edge: in Developer tools, `addEventListener` will also be patched by `zone.js`. 
-  in Edge the performance will be slowed down, and the `performance monitor` data will be wrong because of the `zone.js` patch.
- in some version of `IE11`, the `addEventListener` will throw exception because of the `security` error.
`zone.js` will check those cases and if the code is run in `IE/Edge` developer tools, just use `native addEventListener` to prevent such kind of performance impact or error.
To do this check, `zone.js` will call `callback.toString()` (callback is the handler in  `addEventListener(eventName, callback);`) , and in `IE/Edge` and some version of `Firefox`, the `callback.toString()` will …
> feat(@schematics/angular): add flag for IE/Edge to prevent error or performance impact

- packages/angular_devkit/schematics/src/sink/filesystem.ts
- tslint.json
This should be part of the next minor release, not a patch release as it could cause issues with consumers of the schematics library that are not using pipeable operators.
> style: Add tslint rule to prevent using non-pipeable imports

- packages/angular_devkit/schematics/collection-schema.json
- packages/angular_devkit/schematics/src/engine/collection.ts
- packages/angular_devkit/schematics/src/engine/engine.ts
- packages/angular_devkit/schematics/src/engine/interface.ts
- packages/angular_devkit/schematics/tools/fallback-engine-host.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts
- packages/angular_devkit/schematics/tools/file-system-engine-host_spec.ts
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-basic-string/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-basic/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-circular-deep/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-circular-middle/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-circular-multiple/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-circular/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-deep/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-multiple/collection.json
- tests/@angular_devkit/schematics/tools/file-system-engine-host/extends-replace/collection.json
Example usage (also supports an array of strings):
```{
"name": "extends-basic-string",
"extends": "works",
"schematics": {
"schematic2": {
"description": "2",
"factory": "../null-factory"
}
}
}
```
Closes #34
> feat(@angular-devkit/schematics): support collection extension

- packages/angular_devkit/core/src/virtual-fs/host/memory.ts
- packages/angular_devkit/core/src/virtual-fs/host/memory_spec.ts
- packages/angular_devkit/core/src/virtual-fs/path.ts
- packages/angular_devkit/core/src/virtual-fs/path_spec.ts
- packages/angular_devkit/schematics/src/tree/common_spec.ts
- packages/angular_devkit/schematics/src/tree/filesystem_spec.ts
- packages/angular_devkit/schematics/src/tree/virtual.ts
- packages/angular_devkit/schematics/src/tree/virtual_spec.ts
- the getter `subdirs` in class `VirtualDirEntry` was wrongly implemented,
returning irrelevant data. Make some code common between `subdirs`
and `subfiles` for clarity and DRY respect.
- testing was not done properly either, since a `FileSystemTree` instance was used
(creating corresponding `FileSystemDirEntry` instances) in a test for `VirtualTree`
(and its corresponding model `VirtualDirEntry`). Despite the inheritance,
it wouldn't test it properly. Therefore copy this test as is to the proper file
`filesystem_spec.ts` and slightly adapt it in `virtual_spec.ts` to use the proper
implementations instead.
> fix(@angular-devkit/schematics): VirtualDirEntry#subdirs & proper testing

- WORKSPACE
it has a transitive dep on an updated tsickle that picks up a fix in source-map typings
> fix(bazel): update to newer rules_typescript

- packages/schematics/angular/application/files/__sourcedir__/environments/environment.ts
in `zone.js`, there is a module `zone-error` will monkey-patch global `Error`, and provide
- stack frame with zone name
```javascript
at a.b.c (vendor.bundle.js: 12345 <angular>)
at d.e.f (main.bundle.js: 23456 <root>)
```
- ignore zone aware stack frames
without `zone-error`, we will see a lot of zone stack frames.
```javascript
at zone.run (polyfill.bundle.js: 3424)
at zoneDelegate.invokeTask (polyfill.bundle.js: 3424)
at zoneDelegate.runTask (polyfill.bundle.js: 3424)
at zone.drainMicroTaskQueue (polyfill.bundle.js: 3424)
at a.b.c (vendor.bundle.js: 12345 <angular>)
at d.e.f (main.bundle.js: 23456)
```
it is hard to debug.
with `zone-error`, most of zone stack frames will be removed.
```javascript
at a.b.c (vendor.bundle.js: 12345 <angular>)
at d.e.f (main.bundle.js: 23456 <root>)
```
> feat(@schematics/angular): add zone-error import in polyfill

- packages/schematics/angular/application/files/__dot__gitignore
Ignore yarn-error.log file as well as npm-debug.log
> fix(schematics/angular): ignore yarn-error.log

- package-lock.json
- package.json
- scripts/patch-dependencies.ts
- scripts/patches/rxjs-ts27.patch
- scripts/patches/rxjs-typings.patch
- tsconfig.json
This adds some temporary patches for rxjs.  Once v6.0 is released and the devkit transitions, we can remove them.
> build: compile with TS 2.7

- packages/angular_devkit/core/src/utils/array.ts
- packages/angular_devkit/core/src/utils/index.ts
- packages/angular_devkit/schematics/BUILD
- packages/angular_devkit/schematics/src/engine/engine.ts
- packages/angular_devkit/schematics/src/engine/interface.ts
- packages/angular_devkit/schematics/src/exception/exception.ts
- packages/angular_devkit/schematics/src/index.ts
- packages/angular_devkit/schematics/src/tree/filesystem.ts
- packages/angular_devkit/schematics/src/workflow/index.ts
- packages/angular_devkit/schematics/src/workflow/interface.ts
- packages/angular_devkit/schematics/tasks/node/index.ts
- packages/angular_devkit/schematics/tasks/run-schematic/executor.ts
- packages/angular_devkit/schematics/tasks/run-schematic/init-task.ts
- packages/angular_devkit/schematics/tasks/run-schematic/options.ts
- packages/angular_devkit/schematics/tools/index.ts
- packages/angular_devkit/schematics/tools/workflow/node-workflow.ts
- packages/angular_devkit/schematics_cli/bin/schematics.ts
Workflows are complete abstraction of the whole system. This makes it easier to
have tools that dont diverge from the standard definition of schematics. In case
tools have to diverge they can implement their own workflow as well.
Please note that workflows are also recursive. This means that you can execute
a schematic inside another schematic. This will happen in the next commit with
the schematic task.
For now, the workflow is relatively crude. It will be improved over then next
few commits.
> feat(@angular-devkit/schematics): add a workflow class that simplifies the whole thing

- .circleci/bazel.rc
- .circleci/config.yml
I suspect this will fix the crashes in the TypeScript worker
> build: add CI-specific Bazel settings

- packages/angular_devkit/schematics/src/index.ts
- packages/angular_devkit/schematics/src/sink/dryrun.ts
- packages/angular_devkit/schematics/src/sink/host.ts
Right now rename(a => b) then create(a) should work, but results in an
error that the file already exist.
> fix(@angular-devkit/schematics): fix order of commit for sinks

- .appveyor.yml
- .circleci/config.yml
- package-lock.json
- package.json
- packages/angular_devkit/build_webpack/test/utils/default-workspaces.ts
- tests/@angular_devkit/build_optimizer/webpack/aio-app/package.json
- tests/@angular_devkit/build_optimizer/webpack/simple-app/package.json
This is preferable to updating each time because it can download a new version of chromedriver that is incompatible with the Chrome version on CI.
> ci: update webdriver manually

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
> fix(@angular-devkit/build-optimizer): support fesm5 paths

- .monorepo.json
- packages/_/devkit/collection.json
- packages/_/devkit/package.json
- packages/_/devkit/package/factory.ts
- packages/_/devkit/package/project-files/__path__/README.md
- packages/_/devkit/package/project-files/__path__/package.json
- packages/_/devkit/package/project-files/__path__/src/index.ts
- packages/_/devkit/package/schema.d.ts
- packages/_/devkit/package/schema.json
- tsconfig.json
Took me 15 minutes.
Add a new schematic package "devkit" (unpublished) that contains schematics
for the devkit.
To use, use something like:
```
schematics devkit:package --name=my-test-package --description="Some Description" --displayName="test"
```
> feat(devkit): add a devkit package schematic

- packages/angular_devkit/architect/src/architect.ts
- packages/angular_devkit/architect/src/architect_spec.ts
- packages/angular_devkit/architect/src/targets-schema.json
- packages/angular_devkit/architect_cli/bin/architect.ts
- packages/angular_devkit/build_webpack/src/dev-server/index.ts
- packages/angular_devkit/build_webpack/src/extract-i18n/index.ts
- packages/angular_devkit/build_webpack/src/protractor/index.ts
- packages/angular_devkit/build_webpack/test/utils/run-target-spec.ts
Listing project targets requires the target map to be loaded and validated when Architect is loaded.
This in turn simplifies the API by making `getBuilderConfiguration()` not need to return an observable.
> List target names in Architect

- packages/schematics/angular/service/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.service.ts
- packages/schematics/angular/service/index.ts
- packages/schematics/angular/service/index_spec.ts
- packages/schematics/angular/utility/ast-utils.ts
Change the 'service' schematic for Angular to generate a tree-shakeable
service by default. This greatly simplifies the schematic since it no longer
needs to add a provider to @NgModule.
> feat(@angular-devkit/schematics): generate tree-shakeable services by default

- package-lock.json
- package.json
- packages/angular_devkit/build_webpack/package.json
Removes a deprecation warning message during builds.
> refactor(@angular-devkit/build-webpack): update circular dep plugin

- scripts/snapshots.ts
This prevents deleted files from being kept in the snapshot.
> build: clear snapshot directory before publishing

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts
- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/package-chunk-sort.ts
- packages/angular_devkit/build_angular/src/browser/schema.json
If lazy, basename of input. If not lazy, just "styles" or "scripts".
> fix(@angular-devkit/build-angular): default bundleName logic

- packages/schematics/angular/workspace/files/package.json
`codelyzer@4.2.x` is the most prominent as it provides support for Angular 6
> feat(@schematics/angular): update new project utility dependencies

- packages/schematics/angular/workspace/files/package.json
The current behaviour is risky if the user does not realize he is using a prod
environment. It could have potential disastrous effects.
By contrast, if the user build a dev build by default, it is trivial for her to
change the package.json to her liking.
This PR reduces the risk while inducing minimal pain on most people.
Fix https://github.com/angular/angular-cli/issues/10191
> fix(@schematics/angular): default to non prod builds on new application

- packages/schematics/angular/library/index.ts
When creating a new library, the paths for lint were false.
Now the correct paths should be set.
CC @filipesilva
> fix(@schematics/angular): Correct paths for linting libraries

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts
Otherwise webpack tries to resolve it and when using yarn will not be able
to find it.
Fix https://github.com/angular/angular-cli/issues/10220
> fix(@angular-devkit/build-angular): always use absolute path for loader

- packages/schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.ts
- packages/schematics/angular/service/index_spec.ts
Other schematics don't have extra comma: this commit aligns the service schematics with the others.
> fix(@schematics/angular): remove extra comma in service

- packages/angular_devkit/schematics/tasks/run-schematic/executor.ts
- packages/angular_devkit/schematics/tasks/run-schematic/options.ts
- packages/angular_devkit/schematics/tasks/run-schematic/task.ts
Allow private schematics to run on the RunSchematic task. Also allow 2 arguments
to the constructor which will call a schematic from the same collection.
> fix(@angular-devkit/schematics): QoL changes for run-schematic

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/stats.ts
Before
```
Date: 2018-04-10T14:39:58.064Z
Hash: 9819722f17ec7c60f5bf
Time: 5642ms
chunk {main} main.js, main.js.map (main) 9.11 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 231 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.09 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.5 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.11 MB [initial] [rendered]
Date: 2018-04-10T14:40:02.821Z - Hash: 7d97903e4271af730b4f - Time: 3539ms
2 unchanged chunks
chunk {lazy-lazy-module} lazy-lazy-module.js, lazy-lazy-module.js.map (lazy-lazy-module) 4.08 kB  [rendered]
chunk {main} main.js, main.js.map (main) 9.84 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map …
```
> fix(@angular-devkit/build-angular): add newline on rebuilds

- packages/schematics/angular/application/files/lint/__tsLintRoot__/tslint.json
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/library/files/__projectRoot__/tslint.json
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/library/schema.d.ts
- packages/schematics/angular/library/schema.json
Here is the initial implementation and fix of https://github.com/angular/devkit/issues/570
Some questions:
1. When i add the `schematics/angular/application/files/root/tslint.json`, the workspace tslint file is not copied when i run `ng new App`, only the extending tslint exists in the created application. Is it not possible to create two files with the same name in different directories or am i missing something?
1. The LibraryOptions don't have a property for prefix, so i just chose `lib` for now. Should i add a prefix property and use it?
1. Should i add tests somewhere?
CC @filipesilva
> feat(@schematics/angular): Add directive and component selector rules

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
This ensures that initial vendor modules are alway placed in the vendor bundle.  And also increases the potential for splitting common modules out of async (lazy route) chunks.
Mitigates angular/angular-cli#10294
> fix(@angular-devkit/build-angular): adjust chunk splitting options

- packages/angular_devkit/core/src/workspace/workspace-schema.json
- packages/angular_devkit/core/src/workspace/workspace-schema.ts
- packages/angular_devkit/core/src/workspace/workspace_spec.ts
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/index_spec.ts
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/ng-new/index.ts
- packages/schematics/angular/ng-new/index_spec.ts
- tests/@angular_devkit/build_angular/hello-world-app/.angular.json
With this PR, the prefixes should work like in pre v6 versions (for applications and ng new).
The prefixes are stored in angular.json per project. The default for applications is `app` and the default for libraries is `lib`.
CC @Brocco @filipesilva
> refactor(@schematics/angular): Add prefix handling

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
Also prevent Build Optimizer from running twice on Angular packages.
Partially address https://github.com/angular/angular-cli/issues/10322.
> fix(@angular-devkit/build-optimizer): remove side effects override

- packages/schematics/angular/migrations/update-6/index.ts
> fix(@schematics/angular): do not error if project already migrated

- packages/angular_devkit/build_angular/src/dev-server/index.ts
Create webpack compiler after webpack config customization.
Fix @angular/devkit#700
> fix(@angular-devkit/build-angular): fix dev server hmr

- packages/angular_devkit/core/BUILD
Add hints of external typings required so they can be substituted by the relevant paths in context where they need to be explicit (e.g. google3).
> Declare expected external typings

- packages/schematics/angular/universal/files/__tsconfigFileName__.json
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
- packages/schematics/angular/universal/schema.json
Fix https://github.com/angular/angular-cli/issues/10343
> fix(@schematics/angular): fix universal tsconfig paths

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
This prevents initial chunks (most importantly polyfills) from being split.  It also allows the creation of an overall application async common chunk for small common modules if the total is greater than 30Kb.
> Lazy chunk Webpack config adjustments

- packages/schematics/angular/app-shell/index.ts
- packages/schematics/angular/app-shell/index_spec.ts
Options are in the "options" key.
Fix angular/angular-cli#10379
> fix(@schematics/angular): generate app-shell options properly

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
This will allow people to override some flags from a base browser target, either from
the command line or from their serve directly.
The options chosen are kinda arbitrary. I simply looked at what made sense.
Fix angular/angular-cli#10304
> fix(@angular-devkit/build-angular): support some browser options in dev-server

- package.json
- packages/angular_devkit/build_angular/package.json
All packages now use `~6.4.0`.
> fix(@angular-devkit/build-angular): sync ajv versions

- .gitignore
- packages/angular_devkit/build_ng_packagr/src/build/index.ts
- packages/angular_devkit/build_ng_packagr/src/build/schema.json
- tests/@angular_devkit/build_ng_packagr/ng-packaged/angular.json
- tests/@angular_devkit/build_ng_packagr/ng-packaged/projects/lib/src/lib/lib.service.ts
- tests/@angular_devkit/build_ng_packagr/ng-packaged/projects/lib/tsconfig.lib.json
Add a new tsConfig option in order to permit to use a custom tsConfig file when using @angular-devkit/build-ng-packagr as a build target in angular-cli.
This is, for example, needed in order to resolve this kind of issue : 
```
$ ng build -- --project myLib
BUILD ERROR
projects/common/src/lib/foo/bar.directive.ts(134,41): error TS2339: Property 'includes' does not exist on type 'string[]'.
```
See the evolution of tests for an example. This example show how to change the ES level in lib and target 
All the other options are required for now if we don't want to break the build. I will remove them and bump the ng-packagr dependency version in another PR once / if dherges/ng-packagr#786 is released 
No breaking change.
> feat(@angular-devkit/build-ng-packagr): permit to set a custom TsConfig file

- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Enum values were assumed to start with 0 and be digits. But enum values can be anything really.
When a enum declaration was not identified as an enum in a side effect free package, it would be identified as a top level IIFE (in another transform) and assumed pure. This drops the enum.
This PR fixes the behaviour by allowing the enum to be initialized with anything that doesn't have whitespaces. This is still limited and might lead to other false negatives that break things.
We should find a better way of identifying enums.
/cc @clydin
Fix https://github.com/angular/angular/issues/23400
> fix(@angular-devkit/build-optimizer): don't assume enum values

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts
Fix https://github.com/angular/devkit/issues/763
> fix(@angular-devkit/build-angular): avoid reusing main chunk for common modules

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/application/schema.json
- packages/schematics/angular/library/files/__projectRoot__/ng-package.json
- packages/schematics/angular/library/files/__projectRoot__/package.json
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/library/index_spec.ts
- packages/schematics/angular/utility/validation.ts
fixes angular/angular-cli#10172
> fix(@schematics/angular): Allow for scoped library names

- packages/schematics/angular/universal/files/src/__tsconfigFileName__.json
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/universal/index_spec.ts
- packages/schematics/angular/universal/schema.json
- Create tsconfig.server.json inside the src/ directory of a project
- Set the `entryModule` to 'app/..' instead of 'src/app/..' to adjust for above
- Set the `baseUrl` in tsconfig.server.json
- Properly set the `main` and `tsConfig` entries in the server section of the config file
Fixes https://github.com/angular/angular-cli/issues/10288
> fix(@schematics/angular): fix universal schematic

- packages/schematics/angular/service-worker/files/ngsw-config.json
This should eventually be auto-generated during the `ng add`/etc. operation based on the project's configuration and potentially be augmented at build time for any additional processed resources.
Fixes: angular/angular-cli#10395
> fix(@schematics/angular): update serviceworker config for 6.x files

- packages/angular/pwa/pwa/index.ts
- packages/angular/pwa/pwa/index_spec.ts
> fix(@angular/pwa): Set manifest name if no title is provided

- packages/angular_devkit/schematics/src/rules/base.ts
- packages/schematics/angular/ng-new/index.ts
Sometimes, some actions are not properly optimized. I havent had time to fully
investigate, and we will rework the ActionList entirely (making it more solid
and in line with the rest of the pipeline), so this error will move away properly.
In the meantime, when creating a source, optimizing the tree early helps
tremendously, and since it is not merged (and built from an empty tree),
there is no side effect to optimizing.
> fix(@angular-devkit/schematics): fix __dasherize__ name

- packages/ngtools/webpack/src/paths-plugin.ts
> fix(@ngtools/webpack): Do not apply ts mappings to webpack amd requests

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/service-worker/index.ts
- packages/angular_devkit/build_angular/test/browser/service-worker_spec_large.ts
For most files it doesn't make a difference, but for files that are not UTF-8 encoded (such as `*.ico`, `*.png`, etc) converting to string before hashing creates a different digest than what the ServiceWorker
will generate (see [here][1]). This in turn causes the SW to think the config is wrong and enter a degraded state.
This commit ensures that `ngsw.json` will contain hashes computed in the same way as the SW will compute them.
[1]: https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/service-worker/worker/src/assets.ts#L418
> fix(@angular-devkit/build-angular): hash files as binary

- packages/schematics/angular/application/index.ts
It was using '/src' for the base new project.
> fix(@schematics/angular): use join for sourceRoot

- packages/angular/pwa/pwa/index.ts
- packages/angular/pwa/pwa/schema.d.ts
- packages/angular/pwa/pwa/schema.json
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service-worker/schema.d.ts
- packages/schematics/angular/service-worker/schema.json
Fixes angular/angular-cli#10469 and additionally fixes angular/angular-cli#10352
@hansl @Brocco  @filipesilva
> fix(@angular/pwa): use default project

- packages/angular_devkit/build_angular/src/utils/normalize-asset-patterns.ts
- packages/angular_devkit/build_angular/test/browser/assets_spec_large.ts
Fix https://github.com/angular/angular-cli/issues/10438#issuecomment-385385175
> fix(@angular-devkit/build-angular): build with empty assets array

- packages/angular/pwa/pwa/files/root/manifest.json
- packages/angular/pwa/pwa/index.ts
- packages/angular/pwa/pwa/index_spec.ts
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service-worker/index_spec.ts
- move addition of `manifest.json` in `ng add @angular/pwa` instead of `ng g service-worker` (fixes angular/angular-cli#10512)
- move `npm install` task in `ng g service-worker` instead of `ng add @angular/pwa` (fixes angular/angular-cli#10332 for `ng g service-worker` too, not just `ng add @angular/pwa`)
- move `manifest.json` to `src` instead of `src/assets` (fixes angular/angular-cli#10511, and probably many other yet unforeseen issues)
@hansl @Brocco @filipesilva
> fix(@angular/pwa): move manifest and commands where they belong

- packages/angular_devkit/build_angular/src/dev-server/index.ts
- packages/angular_devkit/build_angular/src/dev-server/schema.json
Fix https://github.com/angular/angular-cli/issues/10559
> feat(@angular-devkit/build-angular): allow poll override in dev-server

- .github/CODEOWNERS
- packages/ngtools/webpack/package.json
This allows the plugin to be used in Angular 5 projects without peerDep warnings.
> fix(@ngtools/webpack): allow TS 2.4 as peerDep

- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums_spec.ts
Big thanks to @clydin for investigation, reproduction and test.
Fix https://github.com/angular/devkit/issues/831
> fix(@angular-devkit/build-optimizer): match comments in enums

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts
They were computationally expensive and returning false negatives.
Fix https://github.com/angular/angular-cli/issues/10605
> fix(@angular-devkit/build-optimizer): remove enum regexes

- packages/schematics/angular/migrations/update-6/index.ts
- packages/schematics/angular/migrations/update-6/index_spec.ts
- packages/schematics/angular/utility/config.ts
Fixes https://github.com/angular/angular-cli/issues/10616
> fix(@schematics/angular): Add budget configuration to update logic

- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
- packages/angular_devkit/build_angular/src/server/index.ts
Using those for server might break the runtime, and since it all runs on the server
we dont need to compress, local name mangling works fine. Also remove the build
optimizer pass on server optimized builds.
Partial fix for angular/angular-cli#8616 (need to have a fix for 1.7.x)
> fix(@angular-devkit/build-angular): remove mangle and compress from server build

- packages/angular_devkit/schematics/src/tree/recorder.ts
- packages/angular_devkit/schematics/src/tree/recorder_spec.ts
- packages/angular_devkit/schematics/src/tree/virtual.ts
Fixes https://github.com/angular/angular-cli/issues/10644
> fix(@angular-devkit/schematics): add support for BOM to UpdateRecorder

- tests/@angular_devkit/core/workspace/angular-workspace.json
In a6767dcc, a defaultProject was added to workspaceJson in workspace_spec, which hasn't been
synced with tests/@angular_devkit/workspace/angular-workspace.json as expected. This was breaking
the related tests with more than one project, like in #739.
> test(@angular-devkit/core): add missing parameter in angular-workspace.json

- packages/schematics/update/update/index.ts
Some third party angular packages contained peer dependencies on `@angular/core` that contained unbounded upper ranges (i.e., `>=2.4.0` or `>=5.0.0`).  This case is now handled in the update logic.
Fixes: angular/angular-cli#10621
> fix(@schematics/update): support upper unbounded ranges

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/e2e/files/src/app.e2e-spec.ts
- packages/schematics/angular/e2e/schema.d.ts
- packages/schematics/angular/e2e/schema.json
Now that the CLI repects the prefix specified, the generated e2e test should also use it.
Currently a project generated with rc.5 fails the e2e test right away.
Another solution is to avoid giving the prefix option to the e2e schematic, and simply revert the title field of `app.component.ts` to `app`. See #721
> fix(@schematic/angular): e2e should use the prefix

- packages/schematics/update/update/npm.ts
Fixes https://github.com/angular/angular-cli/issues/10596
> fix(@schematics/update): Allow usage strict SSL configuration

- packages/ngtools/webpack/src/compiler_host.ts
- packages/ngtools/webpack/src/virtual_file_system_decorator.ts
- packages/ngtools/webpack/src/webpack.ts
> feat(@ngtools/webpack): resolve all file requests with the virtual fs

- packages/schematics/angular/application/other-files/app.component.spec.ts
- packages/schematics/angular/application/other-files/app.component.ts
The current schematic creates a new AppComponent with the value of the title property set to `app` (the value of `prefix` in the schematic). 
With the support of multiple projects it makes more sense to use the app name, so if you run `ng generate application admin` the initial page will reflect that: `Welcome to admin`.
> feat(@schematics/angular): use application name as title in AppComponent

- packages/schematics/angular/application/index.ts
- packages/schematics/angular/e2e/files/src/app.e2e-spec.ts
- packages/schematics/angular/e2e/schema.d.ts
- packages/schematics/angular/e2e/schema.json
PR #906 updated the app schematics to display the name of the app in the title,
so the e2e test has to be fixed.
The prefix is now useless (it was introduced by #720 to fix the e2e test when it was using prefix),
and has been removed.
This a follow up to fix a regression introduced by #906 and released in 6.0.x
> fix(@schematics/angular): e2e should use the name

- packages/schematics/angular/migrations/update-6/index.ts
- packages/schematics/angular/migrations/update-6/index_spec.ts
Fix https://github.com/angular/angular-cli/issues/10647
> fix(@schematics/update): show warning for allowOutsideOutDir assets

- package-lock.json
- package.json
- packages/schematics/angular/workspace/files/package.json
- tests/@angular_devkit/build_angular/hello-world-app/package.json
The only breaking changes in v2 are dropping node 4 support which was never supported by the CLI anyway so this shouldn't affect any users.
> fix(@angular-devkit/build-angular): upgrade coverage reporter

- packages/angular/pwa/pwa/index.ts
- packages/angular/pwa/pwa/index_spec.ts
Adding this line to the body will give us a 100 score in lighthouse for PWA.
Hosted site (with added `<noscript>` tag): https://angular-cli-pwa.firebaseapp.com/
Thanks so much to @Brocco for providing a great example to follow for manipulating the html file. A few of the updates are to make the variable names more semantic given the similar usage.
> feat(@angular/pwa): add content for when javascript is not available

- packages/schematics/angular/collection.json
Currently, if you run `ng generate app admin`, you will receive this error:
```
Schematic "app" not found in collection "@schematics/angular".
```
This patch adds the alias `app` to the `application` schematic.
> feat(@schematics/angular): use app as an alias for the application schematic

- package-lock.json
- package.json
- packages/angular_devkit/build_angular/package.json
Due to reported memory/performance issues with 4.7+, temporarily downgrading back to 4.6 while investigations are performed.
Ref: https://github.com/angular/angular-cli/issues/10897
Devkit CI tests runs are also flaking more often as a result.
> fix(@angular-devkit/build-angular): temporarily downgrade webpack to 4.6

- packages/schematics/package_update/utility/npm.ts
Around 26-05-2018 the http call to npm started failing. Using https instead seems to fix it.
> fix(@schematics/package-update): use https for npm call

- packages/ngtools/webpack/src/angular_compiler_plugin.ts
Supersedes https://github.com/angular/devkit/pull/960
> feat(@ngtools/webpack): allow custom platform transformers

- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts
- packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer_spec.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts
- packages/angular_devkit/build_optimizer/src/transforms/prefix-functions_spec.ts
These fixes should allow projects using `"target": "es2015",` in `tsconfig.json` to create a working build when using Build Optimizer.
For a new project, using a production build, the main bundle size is:
- ES5: with build optimizer 155 kB, without build optimizer 255 kB (-39%)
- ES2015: with build optimizer 147 kB, without build optimizer 208 kB (-29%)
For Angular.io, using a production build, the main bundle size is:
- ES5: with build optimizer 479 kB, without build optimizer 732 kB (-34%)
- ES2015: with build optimizer 435 kB, without build optimizer 626 kB (-30%)
The improvements are less dramatic but still there.
> Build Optimizer ES2015 fixes

- package-lock.json
- package.json
- packages/angular_devkit/build_angular/package.json
- packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts
> fix(@angular-devkit/build-angular): remove build optimizer cache

- packages/angular_devkit/build_angular/src/angular-cli-files/utilities/require-project-module.ts
> fix(@angular-devkit/build-angular): favor project node modules with project deps

- packages/schematics/angular/migrations/update-6/index.ts
- packages/schematics/angular/migrations/update-6/index_spec.ts
Fix angular/angular-cli#11012
Remove invalid property `angularCli` when updating from 1.x to 6.x
> fix(@schematics/angular): remove angularCli in Karma when updating

- packages/schematics/angular/class/index.ts
- packages/schematics/angular/class/index_spec.ts
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/component/index_spec.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/directive/index_spec.ts
- packages/schematics/angular/enum/index.ts
- packages/schematics/angular/enum/index_spec.ts
- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/guard/index_spec.ts
- packages/schematics/angular/interface/index.ts
- packages/schematics/angular/interface/index_spec.ts
- packages/schematics/angular/module/index.ts
- packages/schematics/angular/module/index_spec.ts
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/pipe/index_spec.ts
- packages/schematics/angular/service/index.ts
- packages/schematics/angular/service/index_spec.ts
- packages/schematics/angular/utility/project.ts
- packages/schematics/angular/utility/project_spec.ts
fixes angular/angular-cli#10653
> fix(@schematics/angular): Fix usage of sourceRoot configuration value

- packages/schematics/angular/migrations/update-6/index.ts
Fix the invalid configuration in old lint in `.angular-cli.json`, which makes the `ng update @angular/cli` get the error : `Cannot read property 'indexOf' of undefined`, like the angular/angular-cli#10903
> fix(@schematics/angular): fix invalid configuration in lint

- packages/_/devkit/package/factory.ts
- packages/angular/pwa/pwa/index.ts
- packages/angular_devkit/schematics/src/engine/interface.ts
- packages/angular_devkit/schematics/src/rules/call.ts
- packages/schematics/angular/app-shell/index.ts
- packages/schematics/angular/application/index.ts
- packages/schematics/angular/class/index.ts
- packages/schematics/angular/component/index.ts
- packages/schematics/angular/directive/index.ts
- packages/schematics/angular/e2e/index.ts
- packages/schematics/angular/enum/index.ts
- packages/schematics/angular/guard/index.ts
- packages/schematics/angular/interface/index.ts
- packages/schematics/angular/library/index.ts
- packages/schematics/angular/migrations/update-6/index.ts
- packages/schematics/angular/module/index.ts
- packages/schematics/angular/pipe/index.ts
- packages/schematics/angular/service-worker/index.ts
- packages/schematics/angular/service/index.ts
- packages/schematics/angular/universal/index.ts
- packages/schematics/angular/workspace/index.ts
- packages/schematics/package_update/all/index.ts
- packages/schematics/schematics/blank/factory.ts
- packages/schematics/update/migrate/index.ts
Instead of having to call the rule (which is an anti-pattern), the system now understands
that returning a Rule should chain it to this current Rule.
There is no way to do some pattern (like read a file to select between two Rules) without
this feature.
> feat(@angular-devkit/schematics): returning a rule chains it
